
name: Run API Testing

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    continue-on-error: true
    strategy:
      matrix:
        python-version: [3.9]
        rf-version: [6.0.2]
        selenium-version: [4.9.1]
        browser: [headlesschrome]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }} with Robot Framework ${{ matrix.rf-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: latest
        id: setup-chrome

      - run: |
          echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
          ${{ steps.setup-chrome.outputs.chrome-path }} --version

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip==23.3.1
          pip install -r requirements.txt

      - name: Run Robot Framework Suites
        run: |

          pabot --suitesfrom ./Testcase/ --processes 5 -d ./reports/  -i Test  .

        if: always()
        continue-on-error: true
        env:
          ROBOT_EXIT_ON_FAILURE: false

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./reports


  generate_report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download reports
        uses: actions/download-artifact@v2
        with:
          name: reports
          path: reports/

      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v2.4
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          summary: true
          show_passed_tests: true
